### ISSUE TITLE
Labels cleared when clear all fields pressed

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/rivers.run#106]
In the write-up maker, please label the pulldown box for skill so its clearer that something needs to be done.  Or, default it so it has "skill - required". 
![Screen Shot 2020-02-05 at 7 43 40 AM](https://user-images.githubusercontent.com/39062605/73842992-b4893900-47eb-11ea-8ef3-5bea49c5160d.png)
 When the tool first opens, its just a blank box.  So, 4 new writeups done by a first timer person (who will be nameless) did not have skill in them.

**Comment by ecc521** [comment]
This works in Firefox, and appears to be a chrome bug. It also worked in earlier versions of chrome.

**Comment by ecc521** [comment]
I can confirm that "Skill - Required" and "Rating" are specified as the defaults.

**Comment by ecc521** [comment]
Update: ee053ec should fix this.
