### ISSUE TITLE
Have a "preview" function in the write-up for how the river will look

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/rivers.run#111]
The writeup maker is nice, but its hard to know if you've made a mistake that will cause the river writeup not to look right.  If there were a way to preview the write-up in the format it will display on rivers.run, that would be great.  This will also be helpful when reviewing a write-up submitted by someone else to add to the site.

**Comment by ecc521** [comment]
Please explain....
<img width="1130" alt="Screen Shot 2020-09-04 at 12 37 04 PM" src="https://user-images.githubusercontent.com/42424091/92263876-5882b200-eeab-11ea-950c-eb26aa02094b.png">
