### ISSUE TITLE
Correlation Gauges

### ISSUE THREAD

**Issue by ecc521** [ecc521/rivers.run#12]
[I would like to be able to have users enter gages that are relative to other gages - kind of like this](https://www.americanwhitewater.org/content/Gauge2/detail/id/43472/)

**Comment by ecc521** [comment]
Should come with #16

**Comment by ecc521** [comment]
Given the new design, it should be much easier to implement. I'll be working on this at some point.

**Comment by ecc521** [comment]
Here's the plan:

Put the users script inside a web worker, with a execution time limit
Include all USGS gauge data in the web worker.

Then, run the user provided script in an environment like this:

let finishedarray = []
for (let i=0;i<96;i++) {

try {
function getflow(id) {
    return usgsdata[id][i];
}
let res;

//User's Script Goes Here
//User's script must set res

finishedarray.push(res)
}catch (e) {}

}
postMessage(finishedarray)

**Comment by ecc521** [comment]
Since the user may want to rely on older data (like a gauge higher up in the watershed), it should be made available, at least to a certain extent, in addition to available precipitation data.

This would be OK to run in the browser - but having these calculations be done on a server with no significant execution time constraints, and potentially more available data, would be best.

A server could also reduce the amount of time USGS takes - the processing and finding of the exact data we want would only happen once. In addition, some of the unused data could be eliminated, reducing file sizes.

**Comment by coderdojortp** [comment]
Does this handle AW "virtual gauges"?

**Comment by ecc521** [comment]
Possibly.
Some AW virtual gauges appear to be run by USGS, who computes the flow and handles the virtual gauge like a normal gauge. In this case, it will have a USGS number that can be used.

If the virtual gauge is a formula that is used by AW to calculate flow, then rivers.run does not *currently* support it. This issue is asking for support.

**Comment by ecc521** [comment]
I now have a local build with experimental virtual gauge support (quite a bit more to do though)

Virtual gauges will be a Javascript function, which will be passed an array containing information for all of the site numbers in relatedUSGS for that river. It will return an object containing 00060 (cfs) and/or 00065 (feet).

The system is rather complex, however many gauges may require logic to calculate flow (such as those that have to detect dam releases and separate the dam flow from natural flow. A good example of this is the Nantahala cascades - where the AW gauges, which lack logic, epically fail.)

**Comment by ecc521** [comment]
ebd68eb introduced extremely experimental support.

**Comment by ecc521** [comment]
Virtual gauge support has been removed. 
Although the old implementation worked, it was far from ideal. First, data was computed on the client side, potentially leading to delays. Second, each river could only have code for one virtual gauge, meaning that multiple virtual gauges get hacky across different rivers.

The server should calculate virtual gauges in the future. #93 should lead to this.

**Comment by ecc521** [comment]
Correlation gauges have been re-introduced.
