### ISSUE TITLE
Area Writeups

### ISSUE THREAD

**Issue by ecc521** [ecc521/rivers.run#53]
Allow for area/basin information. This will prevent having to link out to Google Doc's on things like the Cheat River basin, allowing for offline viewing, less bandwidth usage, and a better overall experience.

This should probably pop up in a modal when opened.

**Comment by coderdojortp** [comment]
OK, we do still need to figure out how to do this.  I can either publish the google docs to get a shareable link, or you can come up with another plan to have something I can link from the Local Expertise page.

**Comment by ecc521** [comment]
This should have been fixed by #70 
View instructions at https://docs.google.com/document/d/1tk0O3W7lAdzLmUsy4n-iaqJokA25nmmHL_16-oHZdKE

**Comment by ecc521** [comment]
There was an additional requirement to make the river overviews available on pages other than the main page. 

Implementation details will have to be discussed. 
My idea would be to move the logic into allPages.js

**Comment by ecc521** [comment]
Ok! You should be able to use these now. Simply add the following two tags into your HTML (at the bottom is best)

Your page should already be using allPages.js - if you aren't, make sure that you add it.

<script src="overviews.js"></script>
<script src="allPages.js"></script>
