### ISSUE TITLE
Need reliable way to link to a specific river

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/rivers.run#67]
I want to link directly to 1 river from Ed's lists.   Not sure best way to do this.  For example rivers.run/#mather brings up both mather gorge and little falls.  I thought perhaps to use aw tags, but just the number isn't unique enough, and not sure how to do aw: 90 into a hash tag because of the blank.

**Comment by ecc521** [comment]
Hash links are a normal search - and normal searches only search the name, section, tags, and writeup.
This is likely blocked on #50

**Comment by ecc521** [comment]
4e92d50759713eb7b741accbd30e4eb70a699c11 added some advanced search features. They should be enough for these needs (You can specify name and section)
