### ISSUE TITLE
Mark Dam Releases

### ISSUE THREAD

**Issue by coderdojortp** [ecc521/rivers.run#77]
This probably needs some brainstorming, but how should dam release rivers show in your river list?  We can add links to the release schedule (see what AW does now), but is there more that can be done?  Perhaps show to the right of the flow that they are Dam?  or put in another color?  in some cases, natural flow may also be enough to run, so this can't be an all or nothing...

**Comment by ecc521** [comment]
Links to the schedule shouldn't be an issue.
I would prefer not to color based on expected releases, and rather use current conditions. At the same time, I believe that it must be abundantly clear that there is a release - you don't want people seeing natural flow then getting flooded by the additional release.
I was thinking of replacing the Flow Info column with a button that says "Dam - Read More", or something similar. When the button was clicked, we would expand the river, and show natural flow, expected release time, expected release volume, a link to the schedule, then the normal content.

**Comment by ecc521** [comment]
A small dam icon should be shown in the flow info area if the section has a dam.

**Comment by ecc521** [comment]
This was completed by striping dam releases and adding the word dam to the flow info column.
